import React,{useEffect,useState} from 'react';
import { Plus,Paperclip,ExternalLink,ArrowRight,MessageSquare } from 'lucide-react';
import { supabase } from '@/lib/supabaseClient';
import { Field,Owner,Multi,Drawer,ErrorBox,Section,Check } from './Fields';
import { save,loadEvents } from './data';
import { STAGES,FORMATS,CTA_TYPES,PRODUCTION_TYPES,APPROVAL_CHECKS,DISTRIBUTION_CHANNELS,METRICS,QUESTIONS,RESULTS,codeLabel,stageLabel,localInput,toISO,brDate,safeURL,isVideo,transitionError,defaultScript,defaultProduction } from './model';
import type { Data,Item,Topic,Event,Distribution,Asset } from './model';

type Props={item:Item;data:Data;onClose:()=>void;onSaved:()=>Promise<void>;onNewTopic:(seed:Partial<Topic>)=>void;onNewFormat:(topicId:string)=>void};
const TABS=[['geral','Visão geral'],['roteiro','Roteiro / Copy'],['gravacao','Gravação'],['producao','Produção'],['aprovacao','Aprovação'],['publicacao','Publicação'],['distribuicao','Distribuição'],['analise','Análise'],['historico','Histórico']];
export default function ItemDrawer({item,data,onClose,onSaved,onNewTopic,onNewFormat}:Props){
 const [form,set]=useState<Item>(()=>({...item,script:{...defaultScript(),...item.script},production:{...defaultProduction(),...item.production}}));
 const [tab,T]=useState(TABS.some(t=>t[0]===item.stage)?item.stage:'geral');
 const [busy,B]=useState(false),[dirty,D]=useState(false),[error,E]=useState(''),[notice,N]=useState('');
 const [events,Events]=useState<Event[]>([]),[comment,C]=useState('');
 const [dist,Dist]=useState({title:'',channel:'Stories',owner_id:null as string|null,due_at:null as string|null,status:'Pendente',adaptation:''});
 const [learning,L]=useState(item.qualitative.learning||item.qualitative.objections||'');
 const topic=data.topics.find(t=>t.id===item.topic_id)!;const strategy=data.strategies.find(s=>s.id===topic?.strategy_id);
 const owner=(id?:string|null)=>data.users.find(u=>u.id===id||u.auth_user_id===id)?.nome||'Não atribuído';
 const locked=!!form.published_at;
 function edit(key:keyof Item,value:unknown){set(f=>({...f,[key]:value}));D(true);N('')}
 function part(key:'script'|'recording'|'production'|'approval'|'publication'|'qualitative'|'metrics',field:string,value:unknown){set(f=>({...f,[key]:{...f[key],[field]:value}}));D(true);N('')}
 function close(){if(!dirty||window.confirm('Descartar alterações ainda não salvas?'))onClose()}
 async function history(){try{Events(await loadEvents(item,item.topic_id,topic?.strategy_id||item.topic_id))}catch(e:any){E(e.message)}}
 useEffect(()=>{void history()},[item.id]);
 useEffect(()=>{function before(e:BeforeUnloadEvent){if(dirty){e.preventDefault();e.returnValue=''}}window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
 async function persist(extra:Partial<Item>={}){
  const keys: (keyof Item)[]=['title','channel','format','duration_seconds','aspect_ratio','units','cta','owner_id','needs_recording','needs_design','needs_editing','needs_special_approval','stage','scheduled_at','due_at','session_id','priority','script','recording','production','approval','publication','metrics','qualitative','result','analysis_status'];
  const combined={...form,...extra};const payload=Object.fromEntries(keys.map(k=>[k,combined[k]]));
  const updated=await save<Item>('items',payload,form.id,form.revision);set(updated);D(false);await onSaved();await history();return updated;
 }
 async function act(fn:()=>Promise<void>){if(busy)return;B(true);E('');N('');try{await fn()}catch(e:any){E(e.message||'Não foi possível salvar.')}finally{B(false)}}
 async function move(target:typeof form.stage){await act(async()=>{const reason=transitionError(form,target);if(reason)throw new Error(reason);const updated=await persist({stage:target});N(`Conteúdo em ${stageLabel(updated.stage)}.`)})}
 async function upload(files:FileList|null){if(!files?.length)return;await act(async()=>{
   const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Entre novamente no CRM.');
   const uploaded:Asset[]=[];
   for(const file of Array.from(files)){
    if(file.size>104857600)throw new Error('Cada arquivo pode ter até 100 MB. Para arquivos maiores, use o link do Drive.');
    const path=`${auth.user.id}/${item.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;
    const {error}=await supabase.storage.from('marketing-creative-pipeline').upload(path,file,{upsert:false});if(error)throw error;
    uploaded.push({path,name:file.name,size:file.size,type:file.type});
   }
   const production={...form.production,files:[...(form.production.files||[]),...uploaded]};await persist({production});N('Arquivos anexados. A versão anterior permanece no histórico.');
 })}
 async function openAsset(asset:Asset){await act(async()=>{const {data,error}=await supabase.storage.from('marketing-creative-pipeline').createSignedUrl(asset.path,300);if(error||!data?.signedUrl)throw error||new Error('Arquivo indisponível.');window.open(data.signedUrl,'_blank','noopener,noreferrer')})}
 const link=(url?:string,label='Abrir link')=>safeURL(url)?<a className="ec-link" href={safeURL(url)} target="_blank" rel="noreferrer">{label} <ExternalLink size={12}/></a>:null;
 return <Drawer title={form.title} subtitle={`${codeLabel(form)} · ${stageLabel(form.stage)} · versão ${form.creative_version}`} onClose={close} footer={<><span className="ec-muted">{dirty?'Alterações não salvas':'Tudo salvo'} · Horários de Rondônia</span><button type="button" className="ec-button ec-primary" disabled={busy||!dirty} onClick={()=>void act(async()=>{const updated=await persist();N(`Salvo · ${stageLabel(updated.stage)}`)})}>{busy?'Salvando…':'Salvar alterações'}</button></>}>
 <div className="ec-tabs" role="tablist" aria-label="Detalhes do conteúdo">{TABS.map(([k,label])=><button role="tab" type="button" aria-selected={tab===k} key={k} onClick={()=>T(k)}>{label}</button>)}</div>
 <ErrorBox message={error}/>{notice?<div role="status" className="ec-notice">{notice}</div>:null}
 <div role="tabpanel">
 {tab==='geral'?<><Section title="Estratégia → Pauta → Conteúdo"><p className="ec-wide ec-context"><b>{strategy?.title}</b><br/>{strategy?.primary_objective}<br/><span>{topic?.title}</span></p><div className="ec-wide ec-badges"><span>{topic?.hero}</span><span>{topic?.purpose}</span><span>{topic?.funnel}</span></div>
 <Field label="Título do conteúdo" value={form.title} disabled={locked} onChange={v=>edit('title',v)} wide/><Field label="Canal" value={form.channel} disabled={locked} options={Object.keys(FORMATS)} onChange={v=>{edit('channel',v);edit('format',FORMATS[v]?.[0]||'')}}/><Field label="Formato" value={form.format} disabled={locked} options={FORMATS[form.channel]||[]} onChange={v=>edit('format',v)}/><Field label="Duração (segundos)" type="number" min={0} value={form.duration_seconds} onChange={v=>edit('duration_seconds',Number(v))}/><Field label="Proporção" value={form.aspect_ratio} onChange={v=>edit('aspect_ratio',v)} options={['9:16','4:5','1:1','16:9','Livre']}/><Field label="Quantidade de cards / takes" type="number" min={1} value={form.units} onChange={v=>edit('units',Number(v))}/><Owner users={data.users} value={form.owner_id} onChange={v=>edit('owner_id',v||null)}/><Field label="Data e hora previstas" type="datetime-local" value={localInput(form.scheduled_at)} onChange={v=>edit('scheduled_at',toISO(v))}/><Field label="Prazo de entrega" type="datetime-local" value={localInput(form.due_at)} onChange={v=>edit('due_at',toISO(v))}/><Field label="Prioridade" value={form.priority} options={['Baixa','Normal','Alta','Urgente']} onChange={v=>edit('priority',v)}/><Field label="CTA" value={form.cta} disabled={locked} onChange={v=>edit('cta',v)}/>
 {(['needs_recording','needs_design','needs_editing','needs_special_approval'] as const).map((k,i)=><Check key={k} disabled={locked} label={['Necessita gravação','Necessita design','Necessita edição','Necessita aprovação especial'][i]} value={form[k]} onChange={v=>edit(k,v)}/>)}
 </Section><Section title="Movimentar na esteira" hint="É possível voltar etapas. Os requisitos serão conferidos ao avançar."><div className="ec-stage-actions ec-wide">{STAGES.map(([k,label])=><button type="button" key={k} className={`ec-button ${form.stage===k?'ec-primary':''}`} disabled={busy||form.stage===k} onClick={()=>void move(k)}>{label}</button>)}</div><button type="button" className="ec-button" onClick={()=>{if(!dirty||window.confirm('Descartar alterações e criar um novo formato?'))onNewFormat(form.topic_id)}}><Plus size={16}/>Outro formato desta pauta</button></Section></>:null}
 {tab==='roteiro'?<fieldset disabled={locked||busy}><Section title="Desenvolvimento do conteúdo" hint={isVideo(form.format)?'C + A + M³ + C · cada mensagem deve avançar o raciocínio.':'Desenvolva a mensagem no formato escolhido.'}>
 {isVideo(form.format)?<div className="ec-wide ec-stack">{(form.script.takes||[]).map((take,index)=><section className="ec-take" key={index}><h4>Take {index+1} · {take.function}</h4><div className="ec-form-grid">{(['function','format','scene','on_screen','on_screen_at','speech','broll','notes'] as const).map((k,j)=><Field key={k} label={['Função narrativa','Formato','Cena','Texto em tela','Momento em que o texto aparece','Fala','B-roll','Observações para edição'][j]} value={take[k]} onChange={v=>part('script','takes',form.script.takes.map((t,n)=>n===index?{...t,[k]:v}:t))} type={['scene','speech','notes'].includes(k)?'textarea':'text'} wide={['speech','notes'].includes(k)}/>)}<button type="button" className="ec-link" onClick={()=>part('script','takes',form.script.takes.filter((_,n)=>n!==index).map((t,n)=>({...t,number:n+1})))}>Remover take</button></div></section>)}<button type="button" className="ec-button" onClick={()=>part('script','takes',[...form.script.takes,{number:form.script.takes.length+1,function:'Mensagem 3',format:'',scene:'',on_screen:'',on_screen_at:'',speech:'',broll:'',notes:''}])}>Adicionar take</button></div>:form.format==='Carrossel'?<div className="ec-wide ec-stack">{(form.script.cards||[]).map((card,index)=><section key={index} className="ec-take"><h4>Card {index+1}{index===0?' — Capa':''}</h4><div className="ec-form-grid">{(['title','text','visual'] as const).map((k,j)=><Field key={k} label={['Título','Texto do card','Direção visual'][j]} type={j>0?'textarea':'text'} wide value={card[k]} onChange={v=>part('script','cards',form.script.cards.map((c,n)=>n===index?{...c,[k]:v}:c))}/>)}<button type="button" className="ec-link" onClick={()=>part('script','cards',form.script.cards.filter((_,n)=>n!==index))}>Remover card</button></div></section>)}<button type="button" className="ec-button" onClick={()=>part('script','cards',[...form.script.cards,{title:'',text:'',visual:''}])}>Adicionar card</button></div>:<>{(['headline','art_text','visual'] as const).map((k,i)=><Field key={k} label={['Headline','Texto da arte / copy','Direção visual'][i]} value={form.script[k]} type="textarea" onChange={v=>part('script',k,v)} wide/>)}</>}
 </Section><Section title="Thumbnail / capa">{['Conceito','Foto necessária','Expressão','Enquadramento','Fundo','Texto','Hierarquia visual'].map(k=><Field key={k} label={k} value={form.script.thumbnail?.[k]||''} onChange={v=>part('script','thumbnail',{...form.script.thumbnail,[k]:v})}/>)}</Section><Section title="Legenda e CTA"><Field label="Legenda completa" type="textarea" value={form.script.caption} onChange={v=>part('script','caption',v)} wide/><Field label="Tipo de CTA" value={form.script.cta_type} options={CTA_TYPES} onChange={v=>part('script','cta_type',v)}/><Field label="CTA" value={form.script.cta} onChange={v=>part('script','cta',v)}/><Check label="Roteiro / copy completo e revisado" value={form.script.completed} onChange={v=>part('script','completed',v)}/></Section></fieldset>:null}
 {tab==='gravacao'?<Section title="Preparação da gravação"><Field label="Sessão de gravação" value={form.session_id||''} onChange={v=>edit('session_id',v||null)} options={data.sessions.map(s=>({value:s.id,label:`${brDate(s.scheduled_at)} · ${s.title}`}))} wide/><Field label="Status da gravação" value={String(form.recording.status||'Aguardando gravação')} onChange={v=>part('recording','status',v)} options={['Aguardando gravação','Agendado','Gravado parcialmente','Gravado','Regravar']}/><Check label="Roteiro aprovado para gravação" value={!!form.recording.script_approved} onChange={v=>part('recording','script_approved',v)}/>{['Cenário','Roupa','Enquadramento','Props','B-roll necessário','Takes necessários','Observações'].map(k=><Field key={k} label={k} value={String(form.recording[k]||'')} onChange={v=>part('recording',k,v)} type={k==='Observações'?'textarea':'text'} wide={k==='Observações'}/>)}<Field label="Ordem na sessão (opcional)" type="number" min={1} value={String(form.recording.order||'')} onChange={v=>part('recording','order',v)} hint="Sem ordem manual, a lista agrupa cenário e roupa para reduzir trocas."/></Section>:null}
 {tab==='producao'?<fieldset disabled={locked||busy}><Section title="Produção criativa"><Multi label="Tipos de produção" value={form.production.types||[]} options={PRODUCTION_TYPES} onChange={v=>part('production','types',v)}/><Field label="Status de produção" value={form.production.status} onChange={v=>part('production','status',v)} options={['Aguardando produção','Em produção','Revisão interna','Ajustes solicitados','Finalizado']}/><Owner users={data.users} value={form.production.owner_id} onChange={v=>part('production','owner_id',v)}/><Field label="Data de entrada" type="date" value={form.production.started_at||''} onChange={v=>part('production','started_at',v)}/><Field label="Prazo" type="date" value={form.production.deadline||''} onChange={v=>part('production','deadline',v)}/><Field label="Prioridade da produção" value={form.production.priority||'Normal'} onChange={v=>part('production','priority',v)} options={['Baixa','Normal','Alta','Urgente']}/><Field label="Versão do material" value={form.production.version||'1'} onChange={v=>part('production','version',v)}/><Field label="Briefing" value={form.production.brief||''} type="textarea" onChange={v=>part('production','brief',v)} wide/><Field label="Referências" value={form.production.refs||''} type="textarea" onChange={v=>part('production','refs',v)} wide/>{(['canva','drive','final_url'] as const).map((k,i)=><div key={k} className="ec-wide"><Field label={['Link Canva','Link Drive','Link da peça final'][i]} value={form.production[k]||''} onChange={v=>part('production',k,v)} type="url"/>{link(form.production[k])}</div>)}<label className="ec-upload ec-wide"><Paperclip size={16}/>Anexar arquivos (até 100 MB cada)<input type="file" multiple onChange={e=>void upload(e.target.files)}/></label></Section></fieldset>:null}
 {tab==='producao'?(form.production.files||[]).map(asset=><div className="ec-file" key={asset.path}><button type="button" onClick={()=>void openAsset(asset)}>{asset.name} <ExternalLink size={14}/></button><small>{(asset.size/1048576).toFixed(1)} MB</small>{!locked?<button type="button" className="ec-link" onClick={()=>part('production','files',form.production.files.filter(a=>a.path!==asset.path))}>Retirar desta versão</button>:null}</div>):null}
 {tab==='aprovacao'?<Section title={`Aprovar a versão ${form.creative_version}`} hint="Marque cada item após conferir ou registrar que não se aplica. Aprovação com ajustes mantém a peça em revisão."><div className="ec-wide ec-check-grid">{APPROVAL_CHECKS.map(k=><Check key={k} disabled={locked} label={k} value={!!form.approval.checklist?.[k]} onChange={v=>part('approval','checklist',{...form.approval.checklist,[k]:v})}/>)}</div><Field label="Status da aprovação" disabled={locked} value={form.approval.status} options={['Aguardando aprovação','Aprovado','Aprovado com ajustes','Reprovado','Revisar informações']} onChange={v=>part('approval','status',v)}/>{form.needs_special_approval?<Field label="Revisor da aprovação especial" value={form.approval.special_reviewer||''} options={data.users.filter(u=>u.auth_user_id).map(u=>({value:u.auth_user_id!,label:u.nome}))} onChange={v=>part('approval','special_reviewer',v)} hint="Somente o revisor indicado poderá registrar a aprovação."/>:null}<Field label="Comentários da revisão" type="textarea" disabled={locked} value={form.approval.comment||''} onChange={v=>part('approval','comment',v)} wide/>{form.approval.at?<p className="ec-wide ec-help">Aprovação registrada por {owner(form.approval.by)} em {brDate(form.approval.at)} · versão {form.approval.version}.</p>:null}</Section>:null}
 {tab==='publicacao'?<Section title="Publicação e agendamento" hint="Registre aqui o agendamento realizado no canal ou confirme uma publicação já feita."><Field label="Canal" value={form.channel} disabled onChange={()=>{}}/><Owner label="Responsável pela publicação" users={data.users} value={form.publication.owner_id||form.owner_id} onChange={v=>part('publication','owner_id',v)}/><Field label="Data e horário previstos" type="datetime-local" value={localInput(form.scheduled_at)} onChange={v=>edit('scheduled_at',toISO(v))}/><Field label="Status da publicação" value={form.publication.status||'Aguardando agendamento'} disabled={locked} onChange={v=>part('publication','status',v)} options={['Aguardando agendamento','Agendado','Publicado','Erro','Cancelado']}/><Field label="URL do conteúdo publicado" type="url" value={form.publication.url||''} onChange={v=>part('publication','url',v)} wide/>{link(form.publication.url,'Ver publicação')}<Field label="Observações / erro" type="textarea" value={form.publication.notes||''} onChange={v=>part('publication','notes',v)} wide/>{form.published_at?<p className="ec-wide ec-notice">Publicação registrada em {brDate(form.published_at)} às {localInput(form.published_at).slice(11)}. Análise {form.analysis_status==='done'?'concluída':'pendente'}.</p>:null}</Section>:null}
 {tab==='distribuicao'?<><Section title="Plano de distribuição"><p className="ec-wide ec-help">Cada ação tem canal, responsável, data e adaptação própria.</p>{data.distributions.filter(d=>d.item_id===item.id).map(d=><div className="ec-dist ec-wide" key={d.id}><strong>{d.title}</strong><p>{d.channel} · {owner(d.owner_id)} · {brDate(d.due_at)}</p><p>{d.adaptation}</p><Field label="Status da ação" value={d.status} options={['Pendente','Agendado','Concluído','Cancelado']} onChange={v=>void act(async()=>{await save('distributions',{status:v},d.id,d.revision);await onSaved();await history()})}/></div>)}</Section><Section title="Nova ação de distribuição"><Field label="Ação" value={dist.title} onChange={v=>Dist(d=>({...d,title:v}))} hint="Ex.: compartilhar Reels nos Stories; enviar para parceiros." wide/><Field label="Canal da distribuição" value={dist.channel} options={DISTRIBUTION_CHANNELS} onChange={v=>Dist(d=>({...d,channel:v}))}/><Owner users={data.users} value={dist.owner_id} onChange={v=>Dist(d=>({...d,owner_id:v||null}))}/><Field label="Data da ação" type="datetime-local" value={localInput(dist.due_at)} onChange={v=>Dist(d=>({...d,due_at:toISO(v)}))}/><Field label="Adaptação necessária" type="textarea" value={dist.adaptation} onChange={v=>Dist(d=>({...d,adaptation:v}))} wide/><button type="button" className="ec-button" disabled={busy||!dist.title.trim()} onClick={()=>void act(async()=>{await save<Distribution>('distributions',{...dist,item_id:item.id});Dist(d=>({...d,title:'',adaptation:''}));await onSaved();await history();N('Ação adicionada.')})}><Plus size={16}/>Adicionar distribuição</button></Section></>:null}
 {tab==='analise'?<><Section title="Resultados do conteúdo" hint="Preencha dados medidos. Campos vazios significam métrica ainda não informada.">{Object.entries(METRICS).map(([k,label])=><Field key={k} label={label} type="number" min={0} max={k==='retention'?100:undefined} value={form.metrics[k]??''} onChange={v=>part('metrics',k,v===''?null:Number(v))}/>)}<Field label="Classificação do resultado" value={form.result||''} options={RESULTS} onChange={v=>edit('result',v||null)}/></Section><Section title="Análise qualitativa">{Object.entries(QUESTIONS).map(([k,label])=><Field key={k} label={label} type="textarea" value={form.qualitative[k]||''} onChange={v=>part('qualitative',k,v)} wide/>)}<Check label="Análise concluída" value={form.analysis_status==='done'} onChange={v=>edit('analysis_status',v?'done':'pending')}/></Section><Section title="Aprendizado → Nova pauta"><Field label="Aprendizado, comentário ou objeção" type="textarea" value={learning} onChange={L} wide/><div className="ec-wide ec-toolbar"><button type="button" className="ec-button ec-primary" disabled={busy||!learning.trim()} onClick={()=>void act(async()=>{if(dirty)await persist();onNewTopic({strategy_id:topic.strategy_id,source_item_id:item.id,source_learning:learning,source:'Comentário',idea:learning,hero:'HELP',purpose:'Demanda',audiences:topic.audiences,product:topic.product})})}><ArrowRight size={16}/>Gerar nova pauta</button></div></Section></>:null}
 {tab==='historico'?<><Section title="Comentários internos"><Field label="Novo comentário" type="textarea" value={comment} onChange={C} wide/><button type="button" className="ec-button" disabled={busy||!comment.trim()} onClick={()=>void act(async()=>{await save('comments',{item_id:item.id,body:comment});C('');await history();N('Comentário registrado.')})}><MessageSquare size={16}/>Comentar</button></Section><Section title="Histórico do conteúdo" hint="Inclui a estratégia, a pauta e os registros de cada versão."><ol className="ec-timeline ec-wide">{events.map(e=><li key={e.id}><div><strong>{e.kind}</strong><time>{brDate(e.created_at)} · {localInput(e.created_at).slice(11)}</time></div><p>{owner(e.actor_id)}{e.after_data?.stage?` · ${stageLabel(String(e.after_data.stage))}`:''}</p>{e.comment?<p className="ec-prewrap">{e.comment}</p>:<details><summary>Ver alterações e versão</summary><p>{Object.keys(e.after_data||{}).filter(k=>!['revision','updated_at'].includes(k)&&JSON.stringify(e.before_data?.[k])!==JSON.stringify(e.after_data?.[k])).join(' · ')}</p><pre>{JSON.stringify({antes:e.before_data,depois:e.after_data},null,2)}</pre>{((e.after_data?.production as Item['production'])?.files||[]).map(a=><button key={a.path} className="ec-link" onClick={()=>void openAsset(a)}>{a.name}</button>)}</details>}</li>)}</ol></Section></>:null}
 </div></Drawer>;
}
