import React,{useState,useEffect} from 'react';
import { Sparkles } from 'lucide-react';
import { Drawer,Field,ErrorBox } from './Fields';
import { maxRequest,save,PREFIX } from './data';
import { supabase } from '@/lib/supabaseClient';
import { codeLabel,toISO } from './model';
import type { Data,Item,Topic,Script } from './model';
const ACTIONS={pautas:'Sugerir pautas',repeticoes:'Identificar pautas repetidas',ganchos:'Sugerir ganchos',roteiro:'Desenvolver roteiro / copy',legenda:'Desenvolver legenda',cta:'Sugerir CTA',formatos:'Desdobrar em formatos',stories:'Criar sequência de Stories',equilibrio:'Analisar equilíbrio editorial',performance:'Analisar resultados',reaproveitamento:'Recomendar reaproveitamento',comentarios:'Gerar pautas de comentários / objeções',calendario:'Sugerir calendário'};
type Result={summary:string;recommendations:string[];topics:Partial<Topic>[];script?:Script;hooks:string[];caption?:string;cta?:string;calendar:{item_id?:string;title:string;date:string;channel:string;reason:string}[]};
export default function MaxPanel({data,onClose,onSaved,onTopic,strategyId}:{data:Data;onClose:()=>void;onSaved:()=>Promise<void>;onTopic:(seed:Partial<Topic>)=>void;strategyId?:string}){
 const [strategy,S]=useState(strategyId||data.strategies[0]?.id||''),[itemId,I]=useState(''),[action,A]=useState('pautas'),[instructions,Q]=useState(''),[busy,B]=useState(false),[error,E]=useState(''),[notice,N]=useState(''),[result,R]=useState<Result|null>(null),[runs,Runs]=useState<{id:string;action:string;created_at:string;result:Result;item_id:string|null}[]>([]);
 const topics=new Set(data.topics.filter(t=>t.strategy_id===strategy).map(t=>t.id));const items=data.items.filter(i=>topics.has(i.topic_id));const item=data.items.find(i=>i.id===itemId);
 const [resultItemId,RI]=useState(''),[resultStrategyId,RS]=useState('');
 useEffect(()=>{let active=true;void supabase.from(PREFIX+'ai_runs').select('id,action,created_at,result,item_id').eq('strategy_id',strategy).order('created_at',{ascending:false}).limit(20).then(({data,error})=>{if(active){if(error)E(error.message);else Runs(data||[])}});return()=>{active=false}},[strategy,result]);
 async function generate(){B(true);E('');N('');try{const output=await maxRequest({strategy_id:strategy,item_id:itemId||undefined,action,instructions});R(output.result);RI(itemId);RS(strategy)}catch(e:any){E(e.message)}finally{B(false)}}
 async function apply(patch:Partial<Item>,target= item){if(!target)return;B(true);E('');try{await save('items',patch,target.id,target.revision);await onSaved();N('Sugestão aplicada como rascunho. Revise antes de avançar.')}catch(e:any){E(e.message)}finally{B(false)}}
 return <Drawer title="MAX — Estrategista de Conteúdo" subtitle="Estratégia, histórico e resultados orientam cada sugestão." onClose={onClose}><ErrorBox message={error}/>{notice?<div className="ec-notice" role="status">{notice}</div>:null}<div className="ec-form-grid"><Field label="Estratégia de referência" value={strategy} onChange={v=>{S(v);I('');R(null)}} options={data.strategies.map(s=>({value:s.id,label:s.title}))} required wide/><Field label="Conteúdo (quando aplicável)" value={itemId} onChange={I} options={items.map(i=>({value:i.id,label:`${codeLabel(i)} · ${i.title}`}))} wide/><Field label="Como o MAX pode ajudar?" value={action} onChange={A} options={Object.entries(ACTIONS).map(([value,label])=>({value,label}))} wide/><Field label="Orientação, comentário ou objeção" type="textarea" value={instructions} onChange={Q} wide/></div><button className="ec-button ec-primary" disabled={busy||!strategy} onClick={()=>void generate()}><Sparkles size={16}/>{busy?'MAX está trabalhando…':'Consultar MAX'}</button>
 {result?<section className="ec-max-result"><h3>Leitura estratégica</h3><p className="ec-prewrap">{result.summary}</p><ul>{result.recommendations.map((r,n)=><li key={n}>{r}</li>)}</ul>{result.topics?.map((topic,n)=><div className="ec-panel" key={n}><strong>{topic.title}</strong><p>{topic.idea}</p><div className="ec-badges"><span>{topic.hero}</span><span>{topic.purpose}</span></div><button className="ec-button" onClick={()=>onTopic({...topic,strategy_id:resultStrategyId,source:'IA'})}>Revisar e criar pauta</button></div>)}{result.hooks?.length?<><h3>Ganchos</h3><ul>{result.hooks.map((h,n)=><li key={n}>{h}</li>)}</ul></>:null}{result.script?<><h3>Roteiro / copy sugerido</h3><div className="ec-max-script">{result.script.takes?.map((t,n)=><section key={n}><b>Take {n+1} · {t.function}</b><p>{t.speech}</p><small>Cena: {t.scene}<br/>Texto em tela: {t.on_screen} · {t.on_screen_at}<br/>B-roll: {t.broll}<br/>{t.notes}</small></section>)}{result.script.cards?.map((c,n)=><section key={n}><b>Card {n+1} · {c.title}</b><p>{c.text}</p><small>{c.visual}</small></section>)}<p>{result.script.headline}</p><p>{result.script.art_text}</p><p>{result.script.caption}</p><p>{result.script.cta}</p></div>{resultItemId===itemId&&item&&!item.published_at?<button className="ec-button" disabled={busy} onClick={()=>void apply({script:{...result.script!,completed:false}})}>Aplicar ao roteiro como rascunho</button>:null}</>:null}
 {result.caption?<><h3>Legenda</h3><p className="ec-prewrap">{result.caption}</p>{resultItemId===itemId&&item&&!item.published_at?<button className="ec-button" disabled={busy} onClick={()=>void apply({script:{...item.script,caption:result.caption!,completed:false}})}>Aplicar legenda</button>:null}</>:null}{result.cta?<><h3>CTA</h3><p>{result.cta}</p>{resultItemId===itemId&&item&&!item.published_at?<button className="ec-button" disabled={busy} onClick={()=>void apply({script:{...item.script,cta:result.cta!,completed:false}})}>Aplicar CTA</button>:null}</>:null}
 {result.calendar?.map((c,n)=>{const target=data.items.find(i=>i.id===c.item_id);return <div className="ec-panel" key={n}><strong>{c.title}</strong><p>{c.date} · {c.channel}</p><p>{c.reason}</p>{target&&!target.published_at?<button className="ec-button" disabled={busy} onClick={()=>{const date=toISO(c.date);if(!date||Number.isNaN(new Date(date).getTime())){E('O MAX sugeriu uma data inválida. Ajuste-a no calendário.');return}void apply({scheduled_at:date},target)}}>Aplicar data prevista</button>:null}</div>})}</section>:null}
 {runs.length?<section className="ec-section"><h3>Consultas anteriores desta estratégia</h3>{runs.map(run=><button className="ec-history-run" key={run.id} onClick={()=>{R(run.result);RI(run.item_id||'');RS(strategy);I(run.item_id||'')}}>{new Date(run.created_at).toLocaleString('pt-BR',{timeZone:'America/Porto_Velho'})} · {ACTIONS[run.action as keyof typeof ACTIONS]}</button>)}</section>:null}</Drawer>;
}
