import React,{useState} from 'react';
import { Field,Owner,Multi,Drawer,Submit,ErrorBox,Section,Check } from './Fields';
import { save } from './data';
import { OBJECTIVES,AUDIENCES,PRODUCTS,HERO,PURPOSE,FUNNELS,SOURCES,FORMATS,METRICS,defaultScript,defaultProduction,today,toISO,localInput } from './model';
import type { Data,Strategy,Topic,Item,Session,Mix } from './model';

type Props={data:Data;onClose:()=>void;onSaved:()=>Promise<void>|void};
function closeDirty(dirty:boolean,onClose:()=>void){if(!dirty||window.confirm('Descartar alterações ainda não salvas?'))onClose()}
export function StrategyEditor({data,initial,onClose,onSaved}:{initial?:Strategy}&Props){
 const date=today();const [form,set]=useState(()=>initial||{title:'',kind:'Estratégia Mensal',start_date:date.slice(0,7)+'-01',end_date:new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),0,12).toISOString().slice(0,10),owner_id:null,campaign_id:null,status:'Rascunho',primary_objective:'Gerar autoridade',secondary_objectives:[],audiences:[],focus_products:[],message:'',editorial_mix:{mode:'percent',HERO:20,HUB:50,HELP:30} as Mix,purpose_mix:{mode:'percent',Marca:40,Demanda:40,Comercial:20} as Mix,kpis:[],planned_count:12});
 const [dirty,D]=useState(false),[busy,B]=useState(false),[error,E]=useState('');
 function edit(key:string,value:unknown){set(f=>({...f,[key]:value}));D(true)}
 async function submit(e:React.FormEvent){e.preventDefault();B(true);E('');try{
  if(form.end_date<form.start_date)throw new Error('O fim do período deve ser posterior ao início.');
  for(const mix of [form.editorial_mix,form.purpose_mix]){const values=Object.entries(mix).filter(([k])=>k!=='mode').map(([,v])=>Number(v));if(values.some(v=>!Number.isFinite(v)||v<0))throw new Error('Informe valores válidos para o mix.');if(mix.mode==='percent'&&Math.abs(values.reduce((a,b)=>a+b,0)-100)>.01)throw new Error('Cada mix em percentual deve somar 100%.');}
  const {id,revision,created_at,...payload}=form as Strategy;await save('strategies',payload,id,revision);await onSaved();onClose();
 }catch(e:any){E(e.message)}finally{B(false)}}
 return <Drawer title={initial?'Editar estratégia':'Nova estratégia'} onClose={()=>closeDirty(dirty,onClose)}> <form id="ec-strategy-form" onSubmit={submit}>
 <ErrorBox message={error}/><Section title="Por que estamos comunicando?">
 <Field label="Nome da estratégia" value={form.title} onChange={v=>edit('title',v)} required wide/>
 <Field label="Tipo" value={form.kind} onChange={v=>edit('kind',v)} options={['Estratégia Mensal','Campanha','Estratégia Pontual']}/><Field label="Status" value={form.status} onChange={v=>edit('status',v)} options={['Rascunho','Planejada','Em execução','Concluída']}/>
 <Field label="Início" type="date" value={form.start_date} onChange={v=>edit('start_date',v)} required/><Field label="Fim" type="date" value={form.end_date} onChange={v=>edit('end_date',v)} required/>
 <Owner users={data.users} value={form.owner_id} onChange={v=>edit('owner_id',v||null)}/><Field label="Campanha" value={form.campaign_id||''} onChange={v=>edit('campaign_id',v||null)} options={data.campaigns.map(c=>({value:c.id,label:c.name}))}/>
 <Field label="Objetivo principal" value={form.primary_objective} onChange={v=>edit('primary_objective',v)} options={OBJECTIVES} required/><Field label="Quantidade de conteúdos planejada" type="number" min={0} value={form.planned_count} onChange={v=>edit('planned_count',Number(v))}/>
 <Multi label="Objetivos secundários" value={form.secondary_objectives} options={OBJECTIVES} onChange={v=>edit('secondary_objectives',v)}/><Multi label="Público prioritário" value={form.audiences} options={AUDIENCES} onChange={v=>edit('audiences',v)}/><Multi label="Produto / estratégia em foco" value={form.focus_products} options={PRODUCTS} onChange={v=>edit('focus_products',v)}/>
 <Field label="Mensagem estratégica do período" type="textarea" value={form.message} onChange={v=>edit('message',v)} hint="O que queremos que o público passe a pensar, entender ou fazer?" wide/>
 </Section>
 {([['editorial_mix','Mix HERO / HUB / HELP',Object.keys(HERO)],['purpose_mix','Mix por finalidade',Object.keys(PURPOSE)]] as const).map(([key,label,keys])=><Section key={key} title={label}><Field label="Definir por" value={form[key].mode} onChange={v=>edit(key,{...form[key],mode:v})} options={[{value:'percent',label:'Percentuais (%)'},{value:'quantity',label:'Quantidades'}]}/>{keys.map(k=><Field key={k} label={k} value={Number(form[key][k]||0)} type="number" min={0} max={form[key].mode==='percent'?100:undefined} onChange={v=>edit(key,{...form[key],[k]:Number(v)})}/>)}</Section>)}
 <Section title="KPIs prioritários"><Multi label="Como mediremos o resultado?" value={form.kpis} options={Object.values(METRICS)} onChange={v=>edit('kpis',v)}/></Section><Submit busy={busy}/>
 </form></Drawer>;
}
export function TopicEditor({data,initial,seed,strategyId,onClose,onSaved}:{initial?:Topic;seed?:Partial<Topic>;strategyId?:string}&Props){
 const [form,set]=useState(()=>initial||{strategy_id:strategyId||data.strategies[0]?.id||'',title:'',idea:'',problem:'',audiences:[],objective:'',product:'',pillar:'',angle:'',hook:'',message:'',cta:'',refs:'',notes:'',hero:'HUB',purpose:'Marca',funnel:'Educação',source:'Ideia interna',source_item_id:null,source_learning:'',...seed} as Topic);
 const [dirty,D]=useState(false),[busy,B]=useState(false),[error,E]=useState('');function edit(k:string,v:unknown){set(f=>({...f,[k]:v}));D(true)}
 async function submit(e:React.FormEvent){e.preventDefault();B(true);E('');try{const {id,revision,created_at,...payload}=form;await save('topics',payload,id,revision);await onSaved();onClose()}catch(e:any){E(e.message)}finally{B(false)}}
 return <Drawer title={initial?'Editar pauta':'Nova pauta'} subtitle="Sobre o que vamos falar?" onClose={()=>closeDirty(dirty,onClose)}><form onSubmit={submit}><ErrorBox message={error}/><Section title="A pauta nasce dentro de uma estratégia">
 <Field label="Estratégia" value={form.strategy_id} onChange={v=>edit('strategy_id',v)} options={data.strategies.map(s=>({value:s.id,label:s.title}))} required wide/><Field label="Título da pauta" value={form.title} onChange={v=>edit('title',v)} required wide/>
 {(['idea','problem','angle','hook','message','cta','refs','notes'] as const).map((k,i)=><Field key={k} label={['Ideia central','Problema / oportunidade','Ângulo','Gancho inicial','Mensagem principal','CTA desejado','Referências','Observações'][i]} type="textarea" value={form[k]} onChange={v=>edit(k,v)} wide/>)}
 <Multi label="Público" value={form.audiences} options={AUDIENCES} onChange={v=>edit('audiences',v)}/><Field label="Objetivo específico" value={form.objective} onChange={v=>edit('objective',v)} options={OBJECTIVES}/><Field label="Produto / estratégia" value={form.product} onChange={v=>edit('product',v)} options={PRODUCTS}/><Field label="Pilar editorial" value={form.pillar} onChange={v=>edit('pillar',v)}/><Field label="Função no funil" value={form.funnel} onChange={v=>edit('funnel',v)} options={FUNNELS}/><Field label="Origem" value={form.source} onChange={v=>edit('source',v)} options={SOURCES}/>
 </Section><Section title="Classificações da pauta"><Field label="HERO / HUB / HELP" value={form.hero} onChange={v=>edit('hero',v)} options={Object.keys(HERO)} required hint={HERO[form.hero]}/><Field label="Finalidade" value={form.purpose} onChange={v=>edit('purpose',v)} options={Object.keys(PURPOSE)} required hint={PURPOSE[form.purpose]}/><div className="ec-wide ec-help">{Object.entries(HERO).map(([k,v])=><p key={k}><b>{k}:</b> {v}</p>)}{Object.entries(PURPOSE).map(([k,v])=><p key={k}><b>{k}:</b> {v}</p>)}</div>{form.source_item_id?<Field label="Aprendizado / comentário que originou a pauta" value={form.source_learning} type="textarea" onChange={v=>edit('source_learning',v)} wide/>:null}</Section><Submit busy={busy}/></form></Drawer>;
}
export function ItemCreator({data,topicId,onClose,onSaved}:{topicId?:string}&Props){
 const [form,set]=useState({topic_id:topicId||data.topics[0]?.id||'',title:'',channel:'Instagram',format:'Reels',duration_seconds:45,aspect_ratio:'9:16',units:6,cta:'',owner_id:null as string|null,needs_recording:true,needs_design:false,needs_editing:true,needs_special_approval:false});
 const [busy,B]=useState(false),[error,E]=useState('');function edit(k:string,v:unknown){set(f=>({...f,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();B(true);try{const topic=data.topics.find(t=>t.id===form.topic_id);await save('items',{...form,title:form.title.trim()||topic?.title,script:defaultScript(),production:defaultProduction()});await onSaved();onClose()}catch(e:any){E(e.message)}finally{B(false)}}
 return <Drawer title="Transformar pauta em conteúdo" subtitle="Cada formato terá um ID e um percurso próprios." onClose={onClose}><form onSubmit={submit}><ErrorBox message={error}/><Section title="Como essa ideia será comunicada?">
 <Field label="Pauta" value={form.topic_id} onChange={v=>edit('topic_id',v)} options={data.topics.map(t=>({value:t.id,label:t.title}))} required wide/><Field label="Título da peça (opcional)" value={form.title} onChange={v=>edit('title',v)} wide hint="Se não preencher, usaremos o título da pauta."/>
 <Field label="Canal" value={form.channel} onChange={v=>set(f=>({...f,channel:v,format:FORMATS[v]?.[0]||''}))} options={Object.keys(FORMATS)} required/><Field label="Formato" value={form.format} onChange={v=>edit('format',v)} options={FORMATS[form.channel]||[]} required/>
 <Field label="Duração (segundos)" type="number" min={0} value={form.duration_seconds} onChange={v=>edit('duration_seconds',Number(v))}/><Field label="Proporção" value={form.aspect_ratio} onChange={v=>edit('aspect_ratio',v)} options={['9:16','4:5','1:1','16:9','Livre']}/><Field label="Quantidade de cards / takes" type="number" min={1} value={form.units} onChange={v=>edit('units',Number(v))}/><Owner users={data.users} value={form.owner_id} onChange={v=>edit('owner_id',v||null)}/><Field label="CTA" value={form.cta} onChange={v=>edit('cta',v)} wide/>
 {(['needs_recording','needs_design','needs_editing','needs_special_approval'] as const).map((k,i)=><Check key={k} label={['Necessita gravação','Necessita design','Necessita edição','Necessita aprovação especial'][i]} value={form[k]} onChange={v=>edit(k,v)}/>)}
 </Section><Submit busy={busy} label="Criar conteúdo"/></form></Drawer>;
}
export function SessionEditor({data,initial,onClose,onSaved}:{initial?:Session}&Props){
 const [form,set]=useState(()=>initial||{title:'',scheduled_at:'',location:'',owner_id:null,presenter:'',videomaker:'',equipment:'',notes:''});const [busy,B]=useState(false),[error,E]=useState('');
 function edit(k:string,v:unknown){set(f=>({...f,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();B(true);try{const {id,revision,created_at,...payload}=form as Session;await save('sessions',payload,id,revision);await onSaved();onClose()}catch(e:any){E(e.message)}finally{B(false)}}
 return <Drawer title={initial?'Editar sessão de gravação':'Nova sessão de gravação'} onClose={onClose}><form onSubmit={submit}><ErrorBox message={error}/><Section title="Grave vários conteúdos em uma sessão"><Field label="Nome da sessão" value={form.title} onChange={v=>edit('title',v)} required wide/><Field label="Data e horário · Rondônia" type="datetime-local" value={localInput(form.scheduled_at)} onChange={v=>edit('scheduled_at',toISO(v))} required/><Owner users={data.users} value={form.owner_id} onChange={v=>edit('owner_id',v||null)}/>{(['location','presenter','videomaker','equipment','notes'] as const).map((k,i)=><Field key={k} label={['Local','Apresentador','Videomaker','Equipamentos necessários','Observações'][i]} value={form[k]} onChange={v=>edit(k,v)} type={i>2?'textarea':'text'} wide={i>2}/>)}</Section><Submit busy={busy}/></form></Drawer>;
}
