import React,{useState} from 'react';
import { useDraggable,useDroppable } from '@dnd-kit/core';
import { GripVertical,Plus,ChevronLeft,ChevronRight,Video,Palette,CheckCircle2,Rocket,BarChart3,CalendarDays } from 'lucide-react';
import { STAGES,METRICS,codeLabel,localDate,localInput,brDate,overdue,produced,weeklyWarnings,metricValue } from './model';
import type { Data,Item,Stage,Strategy,Topic,Session,Mix } from './model';
import { Field } from './Fields';

type ViewProps={items:Item[];data:Data;onOpen:(item:Item)=>void};
export function ContentCard({item,data,onOpen,compact=false}:ViewProps&{item:Item;compact?:boolean}){
 const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:item.id});
 const topic=data.topics.find(t=>t.id===item.topic_id);const user=data.users.find(u=>u.id===item.owner_id);
 return <article ref={setNodeRef} style={transform?{transform:`translate3d(${transform.x}px,${transform.y}px,0)`,zIndex:20,opacity:isDragging ? 0.7 : 1}:undefined} className={`ec-content-card ${overdue(item)?'ec-late':''} ${compact?'ec-compact':''}`}>
 <div className="ec-card-id"><small>{codeLabel(item)}</small><button type="button" className="ec-drag" aria-label={`Arrastar ${item.title}`} {...listeners} {...attributes}><GripVertical size={16}/></button></div>
 <button type="button" className="ec-card-open" onClick={()=>onOpen(item)}><h4>{item.title}</h4><p>{item.channel} · {item.format}</p><div className="ec-badges"><span className={`ec-${topic?.hero?.toLowerCase()}`}>{topic?.hero}</span><span>{topic?.purpose}</span></div><div className="ec-card-meta"><span><CalendarDays size={12}/>{brDate(item.scheduled_at)}</span><span>{user?.nome||'Sem responsável'}</span></div>{!compact?<><div className="ec-card-icons"><span title={item.needs_recording?'Necessita gravação':'Sem gravação'} className={item.needs_recording?'active':''}><Video size={14}/></span><span title={item.needs_design||item.needs_editing?'Necessita criação':'Sem criação'} className={item.needs_design||item.needs_editing?'active':''}><Palette size={14}/></span><span title={`Aprovação: ${item.approval.status}`} className={item.approval.status==='Aprovado'?'done':''}><CheckCircle2 size={14}/></span><span title={`Publicação: ${item.publication.status}`} className={item.published_at?'done':''}><Rocket size={14}/></span><span title={`Análise: ${item.analysis_status==='done'?'concluída':'pendente'}`} className={item.analysis_status==='done'?'done':''}><BarChart3 size={14}/></span></div><p className="ec-card-status">{overdue(item)?'Prazo vencido · ':''}{item.stage==='producao'?item.production.status:item.stage==='gravacao'?item.recording.status:item.stage==='aprovacao'?item.approval.status:item.stage==='publicacao'?item.publication.status:item.analysis_status==='done'?'Analisado':item.priority}</p></>:null}</button></article>;
}
function Column({stage,label,children,count}:{stage:Stage;label:string;children:React.ReactNode;count:number}){const {setNodeRef,isOver}=useDroppable({id:`stage:${stage}`});return <section ref={setNodeRef} className={`ec-column ${isOver?'ec-drop-active':''}`}><header><h3>{label}</h3><span>{count}</span></header><div>{children}</div></section>}
export function Board({items,data,onOpen,strategies,topics,onStrategy,onTopic,onFormat}:{strategies:Strategy[];topics:Topic[];onStrategy:(s?:Strategy)=>void;onTopic:(t?:Topic)=>void;onFormat:(id?:string)=>void}&ViewProps){
 return <div className="ec-board" aria-label="Mesa de operações">{STAGES.map(([stage,label])=>{const group=items.filter(i=>i.stage===stage);return <Column key={stage} stage={stage} label={label} count={group.length+(stage==='estrategia'?strategies.length:stage==='pautas'?topics.length:0)}>
 {stage==='estrategia'?<><button className="ec-column-add" onClick={()=>onStrategy()}><Plus size={14}/>Nova estratégia</button>{strategies.map(s=><button key={s.id} className="ec-planning-card" onClick={()=>onStrategy(s)}><small>{s.kind}</small><strong>{s.title}</strong><p>{s.primary_objective}</p><span>{s.status}</span></button>)}</>:null}
 {stage==='pautas'?<><button className="ec-column-add" onClick={()=>onTopic()}><Plus size={14}/>Nova pauta</button>{topics.map(t=><div className="ec-planning-card" key={t.id}><button onClick={()=>onTopic(t)}><small>PAUTA · {t.hero} · {t.purpose}</small><strong>{t.title}</strong></button><button className="ec-link" onClick={()=>onFormat(t.id)}>Criar formato →</button></div>)}</>:null}
 {stage==='formatos'?<button className="ec-column-add" onClick={()=>onFormat()}><Plus size={14}/>Novo conteúdo</button>:null}
 {group.map(item=><ContentCard key={item.id} item={item} items={items} data={data} onOpen={onOpen}/>)}{!group.length&&!['estrategia','pautas','formatos'].includes(stage)?<p className="ec-drop-hint">Arraste um conteúdo para esta etapa</p>:null}</Column>})}</div>;
}
const keyDate=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function CalendarDay({date,items,data,onOpen,otherMonth}:{date:string;otherMonth:boolean}&ViewProps){const {setNodeRef,isOver}=useDroppable({id:`date:${date}`});return <div ref={setNodeRef} className={`ec-calendar-day ${otherMonth?'ec-other-month':''} ${isOver?'ec-drop-active':''}`}><span>{Number(date.slice(8))}</span>{items.map(item=><ContentCard key={item.id} item={item} data={data} items={items} onOpen={onOpen} compact/>)}</div>}
export function CalendarView({items,data,onOpen,month,onMonth}:{month:string;onMonth:(v:string)=>void}&ViewProps){
 const [mode,M]=useState('month'),[week,W]=useState(0);
 const first=new Date(`${month}-01T12:00:00`);const start=new Date(first);start.setDate(1-((first.getDay()+6)%7)+(mode==='week'?week*7:0));
 const dates=Array.from({length:mode==='week'?7:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return keyDate(d)});
 const weekly=items.filter(i=>dates.slice(0,7).includes(localDate(i.scheduled_at)));
 function advance(n:number){if(mode==='week'){W(w=>w+n)}else{const d=new Date(first);d.setMonth(d.getMonth()+n);onMonth(keyDate(d).slice(0,7));W(0)}}
 return <><div className="ec-toolbar"><button className="ec-icon" aria-label="Período anterior" onClick={()=>advance(-1)}><ChevronLeft size={18}/></button><strong>{mode==='week'?`${brDate(dates[0])} – ${brDate(dates[6])}`:new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(first)}</strong><button className="ec-icon" aria-label="Próximo período" onClick={()=>advance(1)}><ChevronRight size={18}/></button><button className={`ec-button ${mode==='month'?'ec-primary':''}`} onClick={()=>M('month')}>Mensal</button><button className={`ec-button ${mode==='week'?'ec-primary':''}`} onClick={()=>M('week')}>Semanal</button><span className="ec-muted">Arraste uma peça para alterar a data.</span></div><div className="ec-calendar-scroll"><div className="ec-calendar"><div className="ec-calendar-weekdays">{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="ec-calendar-grid">{dates.map(date=><CalendarDay key={date} date={date} items={items.filter(i=>localDate(i.scheduled_at)===date)} data={data} onOpen={onOpen} otherMonth={!date.startsWith(month)}/>)}</div></div></div>
 {mode==='week'?<WeeklyAnalysis items={weekly} data={data}/>:<div className="ec-weekly-grid">{Array.from({length:6},(_,w)=>{const ds=dates.slice(w*7,w*7+7);const list=items.filter(i=>ds.includes(localDate(i.scheduled_at)));return list.length?<section key={w}><h4>{brDate(ds[0])} – {brDate(ds[6])}</h4><WeeklyAnalysis items={list} data={data}/></section>:null})}</div>}
 {items.some(i=>!i.scheduled_at)?<section className="ec-section"><h3>Sem data definida</h3><div className="ec-unscheduled">{items.filter(i=>!i.scheduled_at).map(item=><ContentCard key={item.id} item={item} data={data} items={items} onOpen={onOpen} compact/>)}</div></section>:null}</>;
}
function WeeklyAnalysis({items,data}:{items:Item[];data:Data}){const topics=items.map(i=>data.topics.find(t=>t.id===i.topic_id));const warnings=weeklyWarnings(items,data.topics);return <div className="ec-week-analysis"><div className="ec-badges">{['Marca','Demanda','Comercial','HERO','HUB','HELP'].map(k=><span key={k}>{topics.filter(t=>t?.purpose===k||t?.hero===k).length} {k}</span>)}</div>{warnings.map(w=><p key={w} className="ec-warning">{w}</p>)}{!warnings.length&&items.length?<p className="ec-muted">Nenhum alerta pelas regras de concentração.</p>:null}</div>}
export function ListView({items,data,onOpen}:ViewProps){return <div className="ec-table-scroll"><table className="ec-table"><thead><tr>{['ID / Conteúdo','Estratégia / Pauta','Canal / Formato','Classificações','Responsável','Data prevista','Etapa','Status / Prazo'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{items.map(i=>{const t=data.topics.find(t=>t.id===i.topic_id);return <tr key={i.id}><td><button className="ec-link" onClick={()=>onOpen(i)}><span><small>{codeLabel(i)}</small><br/><strong>{i.title}</strong></span></button></td><td>{data.strategies.find(s=>s.id===t?.strategy_id)?.title}<small>{t?.title}</small></td><td>{i.channel}<small>{i.format}</small></td><td>{t?.hero} · {t?.purpose}<small>{t?.funnel}</small></td><td>{data.users.find(u=>u.id===i.owner_id)?.nome||'Sem responsável'}</td><td>{brDate(i.scheduled_at)}<small>{localInput(i.scheduled_at).slice(11)}</small></td><td>{STAGES.find(s=>s[0]===i.stage)?.[1]}</td><td>{overdue(i)?<span className="ec-warning">Atrasado</span>:i.publication.status}<small>{brDate(i.due_at)}</small></td></tr>})}</tbody></table>{!items.length?<Empty text="Nenhum conteúdo corresponde aos filtros."/>:null}</div>}
export function Performance({items,data,onOpen,metric,onMetric}:{metric:string;onMetric:(v:string)=>void}&ViewProps){const sorted=items.filter(i=>i.published_at).sort((a,b)=>(metricValue(b,metric)??-1)-(metricValue(a,metric)??-1));return <><div className="ec-toolbar"><Field label="Comparar por" value={metric} onChange={onMetric} options={Object.entries(METRICS).map(([value,label])=>({value,label}))}/><p className="ec-muted">Resultados medidos · campos vazios não são considerados no ranking.</p></div><div className="ec-table-scroll"><table className="ec-table"><thead><tr>{['Conteúdo','Canal / formato',METRICS[metric],'Publicado em','Resultado','Análise'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{sorted.map(i=><tr key={i.id}><td><button className="ec-link" onClick={()=>onOpen(i)}>{codeLabel(i)} · {i.title}</button></td><td>{i.channel} · {i.format}</td><td><strong>{metricValue(i,metric)?.toLocaleString('pt-BR')??'—'}</strong></td><td>{brDate(i.published_at)}</td><td>{i.result||'Não avaliado'}</td><td>{i.analysis_status==='done'?'Concluída':'Pendente'}</td></tr>)}</tbody></table>{!sorted.length?<Empty text="As peças publicadas aparecerão aqui para medir resultados e gerar novos aprendizados."/>:null}</div></>}
function MixChart({title,keys,mix,items,topics,total}:{title:string;keys:string[];mix:Mix;items:Item[];topics:Topic[];total:number}){
 const counts=keys.map(k=>{const group=items.filter(i=>{const t=topics.find(t=>t.id===i.topic_id);return t?.hero===k||t?.purpose===k});return {key:k,planned:mix.mode==='percent'?total*Number(mix[k]||0)/100:Number(mix[k]||0),real:group.length,produced:group.filter(produced).length,published:group.filter(i=>i.published_at).length}});
 const max=Math.max(1,...counts.flatMap(c=>[c.planned,c.real,c.produced,c.published]));
 return <section className="ec-panel"><h3>{title}</h3><p className="ec-muted">Meta · Na esteira · Produzido · Publicado</p>{counts.map(c=><div className="ec-mix-row" key={c.key}><strong>{c.key}</strong>{[['planned','Meta'],['real','Na esteira'],['produced','Produzido'],['published','Publicado']].map(([k,label])=><div className={`ec-bar ec-bar-${k}`} key={k}><span>{label}</span><div><i style={{width:`${Number(c[k as keyof typeof c])/max*100}%`}}/></div><b>{Number(c[k as keyof typeof c]).toLocaleString('pt-BR',{maximumFractionDigits:1})}</b></div>)}</div>)}</section>;
}
export function MonthPlan({data,items,strategies,month,onStrategy}:{strategies:Strategy[];month:string;onStrategy:(s:Strategy)=>void}&Omit<ViewProps,'onOpen'>){
 return <div className="ec-month-plan"><h2>Planejamento editorial — {new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(`${month}-01T12:00:00`))}</h2>{strategies.map(s=>{const ids=new Set(data.topics.filter(t=>t.strategy_id===s.id).map(t=>t.id));const group=items.filter(i=>ids.has(i.topic_id));return <section className="ec-strategy-report" key={s.id}><div className="ec-toolbar"><h3>{s.title}</h3><button className="ec-link" onClick={()=>onStrategy(s)}>Editar estratégia</button></div><p>{s.primary_objective} · {s.audiences.join(', ')||'Público a definir'}</p><p className="ec-context">{s.message||'Defina a mensagem estratégica do período.'}</p><div className="ec-badges"><span>{s.planned_count} planejados</span><span>{group.length} na esteira</span><span>{group.filter(produced).length} produzidos</span><span>{group.filter(i=>i.published_at).length} publicados</span></div><div className="ec-report-grid"><MixChart title="HERO / HUB / HELP" keys={['HERO','HUB','HELP']} mix={s.editorial_mix} items={group} topics={data.topics} total={s.planned_count}/><MixChart title="Marca / Demanda / Comercial" keys={['Marca','Demanda','Comercial']} mix={s.purpose_mix} items={group} topics={data.topics} total={s.planned_count}/></div><p className="ec-muted">KPIs: {s.kpis.join(' · ')||'Nenhum KPI selecionado'}</p></section>})}<div className="ec-report-grid">{['Canais','Formatos','Funil'].map((title,index)=>{const counts:Record<string,number>={};items.forEach(i=>{const k=index===0?i.channel:index===1?i.format:data.topics.find(t=>t.id===i.topic_id)?.funnel||'Não definido';counts[k]=(counts[k]||0)+1});return <section className="ec-panel" key={title}><h3>{title}</h3>{Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,n])=><div className="ec-count-row" key={k}><span>{k}</span><b>{n}</b></div>)}</section>})}</div>{!strategies.length?<Empty text="Crie a estratégia do mês para comparar o mix desejado com a operação."/>:null}</div>;
}
export function RecordingDay({data,onOpen,onSession}:{data:Data;onOpen:(i:Item)=>void;onSession:(s?:Session)=>void}){
 const [selected,S]=useState(data.sessions[0]?.id||'');const session=data.sessions.find(s=>s.id===selected);
 const items=data.items.filter(i=>i.session_id===selected).sort((a,b)=>Number(a.recording.order||9999)-Number(b.recording.order||9999)||String(a.recording['Cenário']||'').localeCompare(String(b.recording['Cenário']||''))||String(a.recording.Roupa||'').localeCompare(String(b.recording.Roupa||'')));
 return <><div className="ec-toolbar"><Field label="Sessão de gravação" value={selected} onChange={S} options={data.sessions.map(s=>({value:s.id,label:`${brDate(s.scheduled_at)} · ${s.title}`}))}/><button className="ec-button" onClick={()=>onSession()}>Nova sessão</button>{session?<button className="ec-button" onClick={()=>onSession(session)}>Editar sessão</button>:null}</div>{session?<section className="ec-recording-day"><h2>Roteiro de gravação do dia</h2><p>{session.title} · {brDate(session.scheduled_at)} às {localInput(session.scheduled_at).slice(11)} · {session.location}</p><p>Apresentador: {session.presenter||'A definir'} · Videomaker: {session.videomaker||'A definir'}</p><p>Equipamentos: {session.equipment||'A definir'}</p><p className="ec-muted">Ordem manual, seguida por cenário e roupa para reduzir trocas.</p>{items.map((i,index)=><article className="ec-session-content" key={i.id}><div className="ec-toolbar"><strong>{index+1}. {i.title}</strong><button className="ec-link" onClick={()=>onOpen(i)}>Abrir conteúdo</button></div><p>{codeLabel(i)} · {String(i.recording.status||'Aguardando gravação')} · Roteiro {i.script.completed?'completo':'incompleto'}</p><p>Cenário: {String(i.recording['Cenário']||'—')} · Roupa: {String(i.recording.Roupa||'—')} · Props: {String(i.recording.Props||'—')}</p><p>B-roll: {String(i.recording['B-roll necessário']||'—')}</p><p>Enquadramento: {String(i.recording.Enquadramento||'—')}</p>{i.script.takes?.map((t,n)=><div className="ec-session-take" key={n}><b>Take {n+1} · {t.function}</b><p>{t.speech||'Fala a desenvolver'}</p><small>{t.scene} {t.on_screen?`· Texto: ${t.on_screen} (${t.on_screen_at||'momento a definir'})`:''}</small></div>)}</article>)}{!items.length?<Empty text="Vincule conteúdos a esta sessão no painel de Gravação de cada peça."/>:null}</section>:<Empty text="Crie uma sessão para organizar a gravação de vários conteúdos."/>}</>;
}
export function Empty({text}:{text:string}){return <div className="ec-empty"><p>{text}</p></div>}
