import React,{useCallback,useEffect,useMemo,useState} from 'react';
import { DndContext,PointerSensor,KeyboardSensor,useSensor,useSensors,closestCorners } from '@dnd-kit/core';
import type { DragEndEvent } from '@dnd-kit/core';
import { ArrowLeft,ArrowUpRight,LayoutGrid,CalendarDays,List,BarChart3,Target,Video,Sparkles,Plus,RefreshCw,Search,SlidersHorizontal } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/lib/supabaseClient';
import { loadData,save } from '@/components/marketing/creative/data';
import { EMPTY_DATA,FORMATS,OBJECTIVES,STAGES,METRICS,today,localDate,localInput,toISO,overdue,transitionError,metricValue } from '@/components/marketing/creative/model';
import type { Data,Item,Topic,Strategy,Session,Stage } from '@/components/marketing/creative/model';
import { Field,ErrorBox } from '@/components/marketing/creative/Fields';
import { StrategyEditor,TopicEditor,ItemCreator,SessionEditor } from '@/components/marketing/creative/PlanEditors';
import ItemDrawer from '@/components/marketing/creative/ItemDrawer';
import MaxPanel from '@/components/marketing/creative/MaxPanel';
import { Board,CalendarView,ListView,Performance,MonthPlan,RecordingDay } from '@/components/marketing/creative/Views';
import '@/components/marketing/creative/creative.css';

type Modal={kind:'strategy';value?:Strategy}|{kind:'topic';value?:Topic;seed?:Partial<Topic>}|{kind:'item';topicId?:string}|{kind:'session';value?:Session}|{kind:'detail';value:Item}|{kind:'max'}|null;
const defaultFilters=()=>({month:today().slice(0,7),start:'',end:'',campaign:'',owner:'',channel:'',format:'',objective:'',hero:'',purpose:'',stage:'',status:'',late:'',published:'',query:''});
const VIEWS=[['board','Mesa de Operações',LayoutGrid],['calendar','Calendário',CalendarDays],['list','Lista',List],['performance','Performance',BarChart3],['month','Visão do Mês',Target],['recording','Gravações',Video]] as const;
export default function MarketingCreativePipeline({standalone=false}:{standalone?:boolean}){
 const navigate=useNavigate();const [data,DataState]=useState<Data>(EMPTY_DATA),[loading,L]=useState(true),[busy,B]=useState(false),[error,E]=useState(''),[notice,N]=useState(''),[allowed,Allow]=useState(false);
 const [filters,F]=useState(defaultFilters),[expanded,X]=useState(false),[view,V]=useState('board'),[modal,M]=useState<Modal>(null),[metric,Metric]=useState('leads');
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:7}}),useSensor(KeyboardSensor));
 const reload=useCallback(async()=>{DataState(await loadData())},[]);
 useEffect(()=>{let active=true;void(async()=>{try{const {data:access,error}=await supabase.rpc('marketing_is_admin');if(error)throw error;if(!access)throw new Error('A Esteira Criativa está disponível aos administradores do Marketing.');const loaded=await loadData();if(active){Allow(true);DataState(loaded)}}catch(e:any){if(active)E(e.message)}finally{if(active)L(false)}})();return()=>{active=false}},[]);
 const topicById=useMemo(()=>new Map(data.topics.map(t=>[t.id,t])),[data.topics]);const strategyById=useMemo(()=>new Map(data.strategies.map(s=>[s.id,s])),[data.strategies]);
 const start=filters.start||`${filters.month}-01`,end=filters.end||`${filters.month}-31`;
 const strategies=useMemo(()=>data.strategies.filter(s=>s.start_date<=end&&s.end_date>=start&&(!filters.campaign||s.campaign_id===filters.campaign)),[data.strategies,start,end,filters.campaign]);
 const strategyIds=new Set(strategies.map(s=>s.id));
 const topics=data.topics.filter(t=>strategyIds.has(t.strategy_id)&&(!filters.hero||t.hero===filters.hero)&&(!filters.purpose||t.purpose===filters.purpose)&&(!filters.objective||t.objective===filters.objective)&&(!filters.query||t.title.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR'))));
 const filtered=useMemo(()=>data.items.filter(i=>{
  const t=topicById.get(i.topic_id),s=t?strategyById.get(t.strategy_id):undefined;const day=localDate(i.scheduled_at);const inPeriod=day?day>=start&&day<=end:!!s&&s.start_date<=end&&s.end_date>=start;
  return inPeriod&&(!filters.query||`${i.title} EC-${String(i.code).padStart(5,'0')} ${t?.title}`.toLocaleLowerCase('pt-BR').includes(filters.query.toLocaleLowerCase('pt-BR')))&&(!filters.campaign||s?.campaign_id===filters.campaign)&&(!filters.owner||i.owner_id===filters.owner)&&(!filters.channel||i.channel===filters.channel)&&(!filters.format||i.format===filters.format)&&(!filters.objective||t?.objective===filters.objective||s?.primary_objective===filters.objective)&&(!filters.hero||t?.hero===filters.hero)&&(!filters.purpose||t?.purpose===filters.purpose)&&(!filters.stage||i.stage===filters.stage)&&(!filters.status||[i.production.status,i.recording.status,i.approval.status,i.publication.status].includes(filters.status))&&(!filters.late||overdue(i))&&(!filters.published||(filters.published==='yes'?!!i.published_at:!i.published_at));
 }),[data.items,topicById,strategyById,filters,start,end]);
 const active=filtered.filter(i=>i.publication.status!=='Cancelado');
 const best=active.filter(i=>i.published_at&&metricValue(i,metric)!==null).sort((a,b)=>(metricValue(b,metric)||0)-(metricValue(a,metric)||0))[0];
 const stats=[['Planejados',active.length],['Em produção',active.filter(i=>['roteiro','producao'].includes(i.stage)).length],['Aguardando gravação',active.filter(i=>i.needs_recording&&i.stage==='gravacao'&&i.recording.status!=='Gravado').length],['Aguardando aprovação',active.filter(i=>i.stage==='aprovacao').length],['Programados',active.filter(i=>i.publication.status==='Agendado').length],['Publicados',active.filter(i=>i.published_at).length],['Atrasados',active.filter(i=>overdue(i)).length]];
 function change(key:string,value:string){F(f=>({...f,[key]:value}))}
 async function act(fn:()=>Promise<void>){if(busy)return;B(true);E('');N('');try{await fn()}catch(e:any){E(e.message)}finally{B(false)}}
 async function dragEnd(e:DragEndEvent){if(!e.over||busy)return;const item=data.items.find(i=>i.id===e.active.id);if(!item)return;const target=String(e.over.id);await act(async()=>{
  if(target.startsWith('stage:')){const stage=target.slice(6) as Stage;const reason=transitionError(item,stage);if(reason)throw new Error(reason);await save('items',{stage},item.id,item.revision)}
  else if(target.startsWith('date:')){const date=target.slice(5);const time=localInput(item.scheduled_at).slice(11)||'09:00';await save('items',{scheduled_at:toISO(`${date}T${time}`)},item.id,item.revision)}else return;
  await reload();N('Conteúdo atualizado.');
 })}
 function newTopic(seed?:Partial<Topic>){if(!data.strategies.length){M({kind:'strategy'});N('Crie a estratégia para vincular a primeira pauta.')}else M({kind:'topic',seed})}
 function newItem(topicId?:string){if(!data.topics.length){newTopic();N('Crie uma pauta para escolher os formatos.')}else M({kind:'item',topicId})}
 const onOpen=(value:Item)=>M({kind:'detail',value});
 if(loading)return <div className="ec ec-loading"><RefreshCw className="animate-spin"/>Carregando a Esteira Criativa…</div>;
 if(!allowed)return <div className="ec"><ErrorBox message={error}/></div>;
 return <div className="ec" aria-busy={busy}>
 <header className="ec-hero"><div className="ec-hero-top"><span>CONSULMAX · MARKETING</span>{standalone?<button onClick={()=>navigate('/marketing')}><ArrowLeft size={14}/>Marketing</button>:<button onClick={()=>navigate('/marketing/esteira')}><ArrowUpRight size={14}/>Abrir mesa completa</button>}</div><div className="ec-hero-main"><div><h1>Esteira Criativa<span>.</span></h1><p>Da estratégia ao aprendizado. Toda a operação, no mesmo lugar.</p></div><button className="ec-max-button" onClick={()=>M({kind:'max'})}><Sparkles size={17}/><span>MAX<small>Estrategista de Conteúdo</small></span><ArrowUpRight size={16}/></button></div><div className="ec-hero-bottom"><span>PLANEJAR</span><i/><span>CRIAR</span><i/><span>PRODUZIR</span><i/><span>DISTRIBUIR</span><i/><span>MEDIR</span><i/><span>APRENDER</span></div></header>
 <ErrorBox message={error}/>{notice?<div className="ec-notice" role="status">{notice}</div>:null}
 <div className="ec-controls"><div className="ec-search"><Search size={16}/><input aria-label="Buscar conteúdo" placeholder="Buscar título, pauta ou ID…" value={filters.query} onChange={e=>change('query',e.target.value)}/></div><input type="month" aria-label="Mês da esteira" value={filters.month} onChange={e=>F(f=>({...f,month:e.target.value||today().slice(0,7),start:'',end:''}))}/><button className={`ec-button ${expanded?'ec-selected':''}`} onClick={()=>X(!expanded)}><SlidersHorizontal size={15}/>Filtros</button><button className="ec-icon" aria-label="Atualizar esteira" disabled={busy} onClick={()=>void act(reload)}><RefreshCw size={16}/></button><div className="ec-create-actions"><button className="ec-button" onClick={()=>M({kind:'strategy'})}>Estratégia</button><button className="ec-button" onClick={()=>newTopic()}>Pauta</button><button className="ec-button ec-primary" onClick={()=>newItem()}><Plus size={15}/>Conteúdo</button></div></div>
 {expanded?<div className="ec-filter-grid"><Field label="Período: início" type="date" value={filters.start} onChange={v=>change('start',v)}/><Field label="Período: fim" type="date" value={filters.end} onChange={v=>change('end',v)}/><Field label="Campanha" value={filters.campaign} onChange={v=>change('campaign',v)} options={data.campaigns.map(c=>({value:c.id,label:c.name}))}/><Field label="Responsável" value={filters.owner} onChange={v=>change('owner',v)} options={data.users.map(u=>({value:u.id,label:u.nome}))}/><Field label="Canal" value={filters.channel} onChange={v=>change('channel',v)} options={Object.keys(FORMATS)}/><Field label="Formato" value={filters.format} onChange={v=>change('format',v)} options={[...new Set(Object.values(FORMATS).flat())]}/><Field label="Objetivo" value={filters.objective} onChange={v=>change('objective',v)} options={OBJECTIVES}/><Field label="HERO / HUB / HELP" value={filters.hero} onChange={v=>change('hero',v)} options={['HERO','HUB','HELP']}/><Field label="Finalidade" value={filters.purpose} onChange={v=>change('purpose',v)} options={['Marca','Demanda','Comercial']}/><Field label="Etapa" value={filters.stage} onChange={v=>change('stage',v)} options={STAGES.map(([value,label])=>({value,label}))}/><Field label="Status" value={filters.status} onChange={v=>change('status',v)} options={['Aguardando produção','Em produção','Revisão interna','Ajustes solicitados','Finalizado','Aguardando gravação','Gravado parcialmente','Gravado','Regravar','Aguardando aprovação','Aprovado','Aprovado com ajustes','Reprovado','Revisar informações','Aguardando agendamento','Agendado','Publicado','Erro','Cancelado']}/><Field label="Atrasos" value={filters.late} onChange={v=>change('late',v)} options={[{value:'yes',label:'Somente atrasados'}]}/><Field label="Publicação" value={filters.published} onChange={v=>change('published',v)} options={[{value:'yes',label:'Publicados'},{value:'no',label:'Não publicados'}]}/><button className="ec-link" onClick={()=>F(defaultFilters())}>Limpar filtros</button></div>:null}
 <div className="ec-kpis">{stats.map(([label,n])=><div className={`ec-kpi ${label==='Atrasados'&&Number(n)>0?'ec-kpi-warning':''}`} key={label}><span>{label}</span><strong>{n}</strong></div>)}<button className="ec-kpi ec-kpi-best" onClick={()=>{if(best)onOpen(best);else V('performance')}}><span>Melhor performance · {METRICS[metric]}</span><strong>{best?metricValue(best,metric)?.toLocaleString('pt-BR'):'—'}</strong><small>{best?.title||'Aguardando métricas'}</small></button></div>
 <nav className="ec-view-tabs" aria-label="Visualizações da esteira">{VIEWS.map(([key,label,Icon])=><button aria-current={view===key?'page':undefined} className={view===key?'active':''} key={key} onClick={()=>V(key)}><Icon size={16}/>{label}</button>)}</nav>
 <DndContext sensors={sensors} collisionDetection={closestCorners} onDragEnd={e=>void dragEnd(e)}><main className="ec-workspace">{view==='board'?<Board data={data} items={filtered} strategies={strategies} topics={topics} onOpen={onOpen} onStrategy={value=>M({kind:'strategy',value})} onTopic={value=>value?M({kind:'topic',value}):newTopic()} onFormat={newItem}/>:null}{view==='calendar'?<CalendarView data={data} items={filtered} onOpen={onOpen} month={filters.month} onMonth={v=>change('month',v)}/>:null}{view==='list'?<ListView data={data} items={filtered} onOpen={onOpen}/>:null}{view==='performance'?<Performance data={data} items={filtered} onOpen={onOpen} metric={metric} onMetric={Metric}/>:null}{view==='month'?<MonthPlan data={data} items={filtered} strategies={strategies} month={filters.month} onStrategy={value=>M({kind:'strategy',value})}/>:null}{view==='recording'?<RecordingDay data={data} onOpen={onOpen} onSession={value=>M({kind:'session',value})}/>:null}</main></DndContext>
 <div className="ec-bottom-note">{filtered.length} conteúdo(s) no período · Horários de Rondônia (UTC−4)</div>
 {modal?.kind==='strategy'?<StrategyEditor data={data} initial={modal.value} onClose={()=>M(null)} onSaved={reload}/>:null}
 {modal?.kind==='topic'?<TopicEditor data={data} initial={modal.value} seed={modal.seed} onClose={()=>M(null)} onSaved={reload}/>:null}
 {modal?.kind==='item'?<ItemCreator data={data} topicId={modal.topicId} onClose={()=>M(null)} onSaved={reload}/>:null}
 {modal?.kind==='session'?<SessionEditor data={data} initial={modal.value} onClose={()=>M(null)} onSaved={reload}/>:null}
 {modal?.kind==='detail'?<ItemDrawer key={modal.value.id} item={modal.value} data={data} onClose={()=>M(null)} onSaved={reload} onNewTopic={newTopic} onNewFormat={newItem}/>:null}
 {modal?.kind==='max'?<MaxPanel data={data} onClose={()=>M(null)} onSaved={reload} onTopic={newTopic}/>:null}
 </div>;
}
