const {PGlite}=await import(process.env.CREATIVE_PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.users(id uuid primary key default gen_random_uuid(),auth_user_id uuid references auth.users(id),role text,nome text);
create table public.marketing_campaigns(id uuid primary key default gen_random_uuid(),name text);
create function public.marketing_is_admin() returns boolean language sql stable as $$ select exists(select 1 from public.users where auth_user_id=auth.uid() and role='admin') $$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(id uuid primary key,bucket_id text,name text);
create function storage.foldername(text) returns text[] language sql immutable as $$ select string_to_array($1,'/') $$;
grant usage on schema auth,storage to authenticated,anon;grant select on public.users to authenticated;`);
await db.exec(fs.readFileSync(new URL('../../supabase/migrations/20260922225841_marketing_creative_pipeline.sql',import.meta.url),'utf8'));
console.log('Migration: PASS');
const admin='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values('${admin}'),('${other}');insert into public.users(auth_user_id,role) values('${admin}','admin'),('${other}','seller'); set role authenticated;set request.jwt.claim.sub='${admin}';`);
let assertions=0;
async function reject(sql,params,pattern){try{await db.query(sql,params);throw new Error('Expected rejection: '+pattern)}catch(e){if(!pattern.test(e.message))throw e;assertions++;}}
function assert(v,label){if(!v)throw new Error(label);assertions++;}
let r=await db.query("insert into marketing_creative_strategies(title,start_date,end_date,primary_objective) values('TESTE','2026-09-01','2026-09-30','Gerar autoridade') returning *");const strategy=r.rows[0];
r=await db.query("insert into marketing_creative_topics(strategy_id,title,hero,purpose) values($1,'TESTE','HELP','Demanda') returning *",[strategy.id]);const topic=r.rows[0];
r=await db.query("insert into marketing_creative_items(topic_id,title,channel,format) values($1,'TESTE','Instagram','Post estático') returning *",[topic.id]);let item=r.rows[0];
const q=async (patch)=>{const result=await db.query(`update marketing_creative_items set ${Object.keys(patch).map((k,i)=>`${k}=$${i+1}`).join(',')} where id=$${Object.keys(patch).length+1} returning *`,[...Object.values(patch).map(v=>v&&typeof v==='object'?JSON.stringify(v):v),item.id]);item=result.rows[0];return item;};
await reject("update marketing_creative_items set stage='gravacao' where id=$1",[item.id],/data e o horário/);
await q({scheduled_at:'2026-09-25T13:00:00Z',stage:'roteiro'});
await reject("update marketing_creative_items set stage='gravacao' where id=$1",[item.id],/Conclua o roteiro/);
await q({script:{completed:true,art_text:'Texto aprovado'},stage:'producao'});
await reject("update marketing_creative_items set stage='aprovacao' where id=$1",[item.id],/Anexe um arquivo/);
await q({production:{final_url:'https://example.com/peca.pdf',status:'Finalizado'},stage:'aprovacao'});
const checks=Object.fromEntries(['Copy','Ortografia','Valores','Informações técnicas','Identidade visual','Marca','CTA','Thumbnail','Legenda','Informações regulatórias','Links'].map(k=>[k,true]));
await reject("update marketing_creative_items set approval=$1 where id=$2",[JSON.stringify({status:'Aprovado',checklist:{}}),item.id],/Revise o checklist/);
await q({approval:{status:'Aprovado',checklist:checks}});assert(item.stage==='publicacao'&&item.approval.by===admin&&item.approval.version===item.creative_version,'approval binds server actor/version');
await q({script:{completed:true,art_text:'Texto alterado'}});assert(item.stage==='aprovacao'&&item.approval.status==='Aguardando aprovação','edit invalidates approval');
await reject("update marketing_creative_items set publication=$1 where id=$2",[JSON.stringify({status:'Agendado'}),item.id],/aprovação da versão/);
await q({approval:{status:'Aprovado',checklist:checks}});
await q({publication:{status:'Publicado',url:'https://example.com/post'}});assert(item.published_at&&item.stage==='distribuicao'&&item.analysis_status==='pending','publishing queues analysis');
await reject("update marketing_creative_items set title='Editado' where id=$1",[item.id],/preserva sua versão/);
await reject("update marketing_creative_items set metrics=$1 where id=$2",[JSON.stringify({views:-1}),item.id],/não negativos/);
await reject("update marketing_creative_items set analysis_status='done' where id=$1",[item.id],/resultado e o aprendizado/);
await q({metrics:{views:250,leads:2},qualitative:{learning:'Dúvida sobre liquidez'},result:'Acima da média',analysis_status:'done',stage:'analise'});assert(item.analysis_status==='done','complete analysis');
await db.query("insert into marketing_creative_comments(item_id,body) values($1,'Teste')",[item.id]);
r=await db.query("select * from marketing_creative_events where item_id=$1",[item.id]);assert(r.rows.length>=10&&r.rows.some(e=>e.kind==='comentário')&&r.rows.some(e=>e.kind==='publicação'),'audit all changes');
await reject('delete from marketing_creative_events where item_id=$1',[item.id],/permission denied/);
await reject("insert into marketing_creative_events(entity_table,entity_id,kind) values('fake',$1,'fake')",[item.id],/permission denied/);
r=await db.query('update marketing_creative_items set owner_id=null where id=$1 and revision=0 returning id',[item.id]);assert(r.rows.length===0,'optimistic locking');
await db.exec(`set request.jwt.claim.sub='${other}';`);r=await db.query('select * from marketing_creative_items');assert(r.rows.length===0,'non admin read denied');
await reject("insert into marketing_creative_topics(strategy_id,title,hero,purpose) values($1,'DENY','HUB','Marca')",[strategy.id],/row-level security/);
console.log(`Workflow + RLS: ${assertions} assertions PASS`);await db.close();
