-- Adiciona a logo oficial da Consulmax ao topo dos três modelos de newsletter.
-- A imagem é servida de forma pública e durável pelo próprio domínio do CRM.

update public.marketing_newsletter_templates
set html_template = $tpl$<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,Helvetica,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{{preheader}}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f4f6f8;padding:28px 12px;"><tr><td align="center"><table role="presentation" width="640" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 6px 24px rgba(15,23,42,.08);"><tr><td align="center" style="background:#ffffff;padding:24px 30px 18px;border-top:5px solid #A11C27;border-bottom:4px solid #B5A573;"><img src="https://crm.consulmaxconsorcios.com.br/logo-consulmax.png" width="210" alt="Consulmax Consórcios" style="display:block;width:210px;max-width:70%;height:auto;border:0;margin:0 auto;"><div style="margin-top:10px;font-size:10px;color:#64748b;letter-spacing:1.25px;text-transform:uppercase;">Relacionamento e planejamento</div></td></tr>{{banner}}<tr><td style="padding:34px 32px 32px;"><h1 style="margin:0 0 22px;color:#1E293F;font-size:27px;line-height:1.25;">{{title}}</h1>{{greeting}}{{content}}{{cta}}</td></tr><tr><td style="padding:22px 30px;background:#f8fafc;border-top:1px solid #e2e8f0;color:#64748b;font-size:11px;line-height:1.55;">Esta mensagem foi enviada por Consulmax Consórcios através de <strong>{{from_email}}</strong>.<br>Se não quiser mais receber nossas newsletters, responda este e-mail solicitando a remoção da lista.</td></tr></table></td></tr></table></body></html>$tpl$,
    updated_at = now()
where slug = 'institucional-premium';

update public.marketing_newsletter_templates
set html_template = $tpl$<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#f7f5f4;font-family:Arial,Helvetica,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{{preheader}}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f7f5f4;padding:28px 12px;"><tr><td align="center"><table role="presentation" width="640" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 8px 26px rgba(30,41,63,.10);"><tr><td align="center" style="background:#ffffff;padding:24px 30px 18px;border-top:5px solid #A11C27;border-bottom:1px solid #e2e8f0;"><img src="https://crm.consulmaxconsorcios.com.br/logo-consulmax.png" width="210" alt="Consulmax Consórcios" style="display:block;width:210px;max-width:70%;height:auto;border:0;margin:0 auto;"><div style="margin-top:10px;font-size:10px;color:#A11C27;letter-spacing:1.25px;text-transform:uppercase;">Oportunidades selecionadas</div></td></tr><tr><td style="height:4px;background:#B5A573;font-size:0;line-height:0;">&nbsp;</td></tr>{{banner}}<tr><td style="padding:34px 32px 30px;"><div style="height:3px;width:54px;background:#A11C27;margin-bottom:20px;"></div><h1 style="margin:0 0 22px;color:#1E293F;font-size:28px;line-height:1.22;">{{title}}</h1>{{greeting}}{{content}}{{cta}}</td></tr><tr><td style="padding:22px 30px;background:#1E293F;color:#cbd5e1;font-size:11px;line-height:1.55;">Consulmax Consórcios • <strong style="color:#ffffff;">{{from_email}}</strong><br>Condições, disponibilidade e análises dependem de cada operação. Para sair da lista, responda solicitando a remoção.</td></tr></table></td></tr></table></body></html>$tpl$,
    updated_at = now()
where slug = 'oportunidade-comercial';

update public.marketing_newsletter_templates
set html_template = $tpl$<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#eef1f5;font-family:Georgia,'Times New Roman',serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{{preheader}}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#eef1f5;padding:28px 12px;"><tr><td align="center"><table role="presentation" width="640" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border-radius:14px;overflow:hidden;box-shadow:0 6px 24px rgba(15,23,42,.08);"><tr><td align="center" style="background:#ffffff;padding:24px 32px 18px;border-top:6px solid #1E293F;border-bottom:1px solid #e2e8f0;"><img src="https://crm.consulmaxconsorcios.com.br/logo-consulmax.png" width="210" alt="Consulmax Consórcios" style="display:block;width:210px;max-width:70%;height:auto;border:0;margin:0 auto;"><div style="margin-top:10px;font-family:Arial,Helvetica,sans-serif;font-size:10px;color:#A11C27;letter-spacing:1.3px;text-transform:uppercase;">Conteúdo • Estratégia • Planejamento</div></td></tr><tr><td style="height:4px;background:#B5A573;font-size:0;line-height:0;">&nbsp;</td></tr>{{banner}}<tr><td style="padding:38px 36px 34px;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:11px;font-weight:700;color:#B5A573;letter-spacing:1.3px;text-transform:uppercase;margin-bottom:12px;">Consulmax Insights</div><h1 style="margin:0 0 24px;color:#1E293F;font-size:30px;line-height:1.22;font-weight:700;">{{title}}</h1>{{greeting}}{{content}}{{cta}}</td></tr><tr><td style="padding:22px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;font-family:Arial,Helvetica,sans-serif;color:#64748b;font-size:11px;line-height:1.55;">Recebido de <strong>{{from_email}}</strong>. Conteúdo de caráter informativo. Para não receber novos conteúdos, responda solicitando a remoção.</td></tr></table></td></tr></table></body></html>$tpl$,
    updated_at = now()
where slug = 'conteudo-educativo';