import React,{useEffect,useState}from"react";import{Camera,Upload}from"lucide-react";

const FONTES=["Assalariado","Autônomo","Aposentado","Empresário","Funcionário Público","Motorista","Produtor Rural","Profissional Liberal","Locador ou Proprietário","Do Lar","Faturamento Empresarial","Outro"];
const ESTADOS=["Solteiro(a)","Casado(a)","União Estável","Divorciado(a)","Separado(a)","Viúvo(a)"];

export default function ClienteCadastroSimplificado(p:any){const{readOnly,nome,setNome,birth,setBirth,chamadoComo,setChamadoComo,extra,setExtra,fotoFile,setFotoFile,phoneCountry,setPhoneCountry,phoneCountries,telefone,setTelefone,email,setEmail,buscarCep,cepLoading,onlyDigits,clamp}=p;const[preview,setPreview]=useState("");useEffect(()=>{if(!fotoFile){setPreview("");return}const u=URL.createObjectURL(fotoFile);setPreview(u);return()=>URL.revokeObjectURL(u)},[fotoFile]);const fonte=String(extra?.fonte_renda||extra?.segmentos?.[0]||"");const setFonte=(v:string)=>setExtra((s:any)=>({...s,fonte_renda:v,segmentos:v?[v]:[]}));return <div className="grid grid-cols-1 xl:grid-cols-12 gap-4">
<section className="rounded-2xl border bg-white p-5 xl:col-span-7"><div className="mb-4"><h4 className="m-0 text-base font-extrabold text-slate-900">Identidade</h4><p className="mt-1 text-xs text-slate-500">Dados pessoais e perfil do cliente.</p></div><div className="grid grid-cols-1 gap-4 md:grid-cols-12">
<div className="md:col-span-5"><div className="label">Nome</div><input className="input" value={nome} onChange={(e:any)=>setNome(e.target.value)} disabled={readOnly}/></div>
<div className="md:col-span-3"><div className="label">Data de Nascimento</div><input className="input" type="date" value={birth||""} onChange={(e:any)=>setBirth(e.target.value)} disabled={readOnly}/></div>
<div className="md:col-span-4"><div className="label">Foto</div><label className={`group flex min-h-[92px] items-center gap-3 rounded-2xl border border-dashed p-3 transition ${readOnly?"cursor-default bg-slate-50":"cursor-pointer hover:border-[#A11C27]/50 hover:bg-[#A11C27]/[.03]"}`}><div className="h-14 w-14 shrink-0 overflow-hidden rounded-2xl border bg-slate-100 flex items-center justify-center">{preview||extra?.foto_url?<img src={preview||extra.foto_url} className="h-full w-full object-cover" alt="Prévia"/>:<Camera className="h-5 w-5 text-slate-400"/>}</div><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-extrabold text-slate-800"><Upload className="h-4 w-4"/>Escolher foto</div><div className="mt-1 truncate text-xs text-slate-500">{fotoFile?.name||"JPG, PNG ou WEBP"}</div></div>{!readOnly&&<input type="file" accept="image/*" className="hidden" onChange={(e:any)=>setFotoFile(e.target.files?.[0]||null)}/>}</label></div>
<div className="md:col-span-12"><div className="label">Nome Social</div><input className="input" placeholder="Como o cliente prefere ser chamado" value={chamadoComo||""} onChange={(e:any)=>setChamadoComo(e.target.value)} disabled={readOnly}/></div>
<div className="md:col-span-6"><div className="label">Perfil do Cliente</div><select className="input" value={extra.perfil||"PF Geral"} onChange={(e:any)=>setExtra((s:any)=>({...s,perfil:e.target.value}))} disabled={readOnly}><option value="PF Geral">PF Geral</option><option value="PF Agro">PF Agro</option><option value="PJ">PJ</option></select></div>
<div className="md:col-span-6"><div className="label">Tipo</div><select className="input" value={extra.tipo||"PF"} onChange={(e:any)=>setExtra((s:any)=>({...s,tipo:e.target.value}))} disabled={readOnly}><option value="PF">PF</option><option value="PJ">PJ</option></select></div>
<div className="md:col-span-4"><div className="label">Fonte de Renda</div><select className="input" value={fonte} onChange={(e:any)=>setFonte(e.target.value)} disabled={readOnly}><option value="">Selecione…</option>{fonte&&!FONTES.includes(fonte)&&<option value={fonte}>{fonte}</option>}{FONTES.map(x=><option key={x} value={x}>{x}</option>)}</select></div>
<div className="md:col-span-4"><div className="label">Sexo</div><select className="input" value={extra.sexo||""} onChange={(e:any)=>setExtra((s:any)=>({...s,sexo:e.target.value}))} disabled={readOnly}><option value="">Selecione…</option><option value="M">Masculino</option><option value="F">Feminino</option><option value="O">Outro</option></select></div>
<div className="md:col-span-4"><div className="label">Estado Civil</div><select className="input" value={extra.estado_civil||""} onChange={(e:any)=>setExtra((s:any)=>({...s,estado_civil:e.target.value}))} disabled={readOnly}><option value="">Selecione…</option>{ESTADOS.map(x=><option key={x} value={x}>{x}</option>)}</select></div>
</div></section>
<section className="rounded-2xl border bg-white p-5 xl:col-span-5"><div className="mb-4"><h4 className="m-0 text-base font-extrabold text-slate-900">Contato e Endereço</h4><p className="mt-1 text-xs text-slate-500">Canais de contato e endereço principal.</p></div><div className="grid grid-cols-1 gap-4 md:grid-cols-12">
<div className="md:col-span-7"><div className="label">Telefone</div><div className="grid grid-cols-[minmax(130px,.8fr)_minmax(0,1.2fr)] gap-2"><select className="input" value={phoneCountry} onChange={(e:any)=>setPhoneCountry(e.target.value)} disabled={readOnly}>{phoneCountries.map((c:any)=><option key={c.code} value={c.code}>{c.name} (+{c.dialCode})</option>)}</select><input className="input" value={telefone} onChange={(e:any)=>setTelefone(e.target.value)} disabled={readOnly} inputMode="tel" placeholder="Número"/></div></div>
<div className="md:col-span-5"><div className="label">E-mail</div><input className="input" type="email" value={email} onChange={(e:any)=>setEmail(e.target.value)} disabled={readOnly}/></div>
<div className="md:col-span-5"><div className="label">CEP</div><div className="flex gap-2"><input className="input" value={extra.endereco_cep||""} onChange={(e:any)=>setExtra((s:any)=>({...s,endereco_cep:onlyDigits(e.target.value).slice(0,8)}))} disabled={readOnly} placeholder="00000000"/><button className="btn shrink-0" type="button" onClick={buscarCep} disabled={readOnly||cepLoading}>{cepLoading?"Buscando…":"Buscar"}</button></div></div>
<div className="md:col-span-7"><div className="label">Logradouro</div><input className="input" value={extra.logradouro||""} onChange={(e:any)=>setExtra((s:any)=>({...s,logradouro:e.target.value}))} disabled={readOnly}/></div>
<div className="md:col-span-3"><div className="label">Número</div><input className="input" value={extra.numero||""} onChange={(e:any)=>setExtra((s:any)=>({...s,numero:clamp(e.target.value,20)}))} disabled={readOnly}/></div>
<div className="md:col-span-9"><div className="label">Complemento</div><input className="input" value={extra.complemento||""} onChange={(e:any)=>setExtra((s:any)=>({...s,complemento:e.target.value}))} disabled={readOnly} placeholder="Apto, sala, bloco, referência…"/></div>
<div className="md:col-span-4"><div className="label">Bairro</div><input className="input" value={extra.bairro||""} onChange={(e:any)=>setExtra((s:any)=>({...s,bairro:e.target.value}))} disabled={readOnly}/></div>
<div className="md:col-span-5"><div className="label">Cidade</div><input className="input" value={extra.cidade||""} onChange={(e:any)=>setExtra((s:any)=>({...s,cidade:e.target.value}))} disabled={readOnly}/></div>
<div className="md:col-span-3"><div className="label">UF</div><input className="input" value={extra.uf||""} onChange={(e:any)=>setExtra((s:any)=>({...s,uf:e.target.value.toUpperCase().slice(0,2)}))} disabled={readOnly} maxLength={2}/></div>
</div></section></div>}
