import{useEffect,useState}from"react";import{supabase}from"@/lib/supabaseClient";import{CsRecord,GOOGLE_REVIEW_URL,WorkItem,normalizeCs,waNumber}from"./customerSuccessModel";import{loadCustomerSuccess,saveCustomerSuccess}from"./customerSuccessRepository";
export function useCustomerSuccess(){const[items,setItems]=useState<WorkItem[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[active,setActive]=useState<WorkItem|null>(null),[form,setForm]=useState<CsRecord|null>(null),[userId,setUserId]=useState<string|null>(null),[userName,setUserName]=useState("");
 async function load(){setLoading(true);try{const a=await supabase.auth.getUser(),id=a.data.user?.id||null;setUserId(id);if(id){const{data}=await supabase.from("users").select("nome").eq("auth_user_id",id).maybeSingle();setUserName(String((data as any)?.nome||a.data.user?.email||""));}setItems(await loadCustomerSuccess());}catch(e:any){alert(e?.message||"Erro ao carregar Sucesso do Cliente.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function open(i:WorkItem){setActive(i);setForm(normalizeCs(i.cs))}function close(){if(!saving){setActive(null);setForm(null)}}
 async function persist(r:CsRecord){if(!active)return;await saveCustomerSuccess(active,r);setItems(x=>x.map(i=>i.venda.id===active.venda.id?{...i,cs:normalizeCs(r)}:i));setActive({...active,cs:normalizeCs(r)});setForm(normalizeCs(r));}
 async function attempt(){if(!active||!form)return;try{setSaving(true);const now=new Date().toISOString(),r={...form,status:(form.status==="pendente"||form.status==="agendado"?"em_validacao":form.status)as any,tentativas:Number(form.tentativas||0)+1,contato_em:now,responsavel_id:form.responsavel_id||userId,responsavel_nome:form.responsavel_nome||userName,updated_at:now};await persist(r)}catch(e:any){alert(e?.message||"Erro ao registrar tentativa.")}finally{setSaving(false)}}
 async function save(){if(!active||!form)return;try{setSaving(true);await persist({...form,responsavel_id:form.responsavel_id||userId,responsavel_nome:form.responsavel_nome||userName,updated_at:new Date().toISOString()});alert("Atendimento salvo.")}catch(e:any){alert(e?.message||"Erro ao salvar atendimento.")}finally{setSaving(false)}}
 async function review(){if(!active||!form)return;if(!GOOGLE_REVIEW_URL)return alert("Configure VITE_GOOGLE_REVIEW_URL no Vercel.");const tel=waNumber(active.cliente?.telefone||active.lead?.telefone||active.venda.telefone);if(!tel)return alert("Cliente sem telefone para WhatsApp.");const n=String(active.cliente?.nome||active.lead?.nome||"").split(/\s+/)[0]||"Olá",msg=`Olá, ${n}! Como combinamos, sua opinião é muito importante para nós. Se puder, deixe uma avaliação sobre sua experiência com a Consulmax no Google: ${GOOGLE_REVIEW_URL}`;window.open(`https://wa.me/${tel}?text=${encodeURIComponent(msg)}`,"_blank");const now=new Date().toISOString();await persist({...form,google_review:true,google_review_em:now,updated_at:now});}
 return{items,loading,saving,active,form,setForm,userName,load,open,close,attempt,save,review};}
